### ISSUE TITLE
Update Validate for Enketo 2.8.0.oc-6

### ISSUE THREAD

**Issue by pbowen-oc** [enketo/enketo-validate#104]
Create a new tag for Validate that is compatible with Enketo 2.8.0.oc-6.

- We would also need it to include the remaining fix for https://github.com/OpenClinica/enketo-express-oc/issues/516 when that is available. 

Tag updated to include that other update.

**Comment by pbowen-oc** [comment]
Create new version off of 1.13.1 tag, update the dependencies as below and create a new tag (1.13.1.oc-1)?

"enketo-transformer": "1.43.0",

"enketo-core": "github:enketo/enketo-core#5.18.4.oc"

**Comment by MartijnR** [comment]
Since this version is not published you need to run `npm run prepare` manually, to generate a new client-side JS bundle (that includes the updated Enketo Core version).

**Comment by svadla-oc** [comment]
@MartijnR it looks like since npm v5, `npm run prepare` will be run automatically as part of `npm install` (https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts). We are using npm v6. Could you please confirm if this command still needs to be run separately? If so, does it need to be run after the `npm install` command?

**Comment by svadla-oc** [comment]
Great. Thanks for confirming
